// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/today": {
            "get": {
                "summary": "today handle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "город \n Example: Kazan",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "локализация \n Example: ru",
                        "name": "lang",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "шкала градусов \n Example: Standard,Imperial,Metric",
                        "name": "unit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/weekly": {
            "get": {
                "summary": "Weekly handle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "город \n Example: Kazan",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "локализация \n Example: ru",
                        "name": "lang",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "шкала градусов \n Example: Standard,Imperial,Metric",
                        "name": "unit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0 – версия АПИ",
	Host:             "localhost:8080 – адрес для запросов",
	BasePath:         "/ – базовый адрес (может быть /api или /api/v1)",
	Schemes:          []string{},
	Title:            "Документация – заголовок всей доки",
	Description:      "API для погоды – текстовое описание АПИ",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
